name: Deploy to DEV on PR Merge

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute script on remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /srv/appHome/phpapps/onebooks/
            git pull origin master
            docker compose up -d --build
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "EMAIL=${{ secrets.EMAIL }}" >> .env
            echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
            echo "APP_URL=${{ secrets.APP_URL }}" >> .env
